// LOGIN
POST http://localhost:3000/api/auth HTTP/1.1
content-type: application/json

{
    "user":"leonardo",
    "password":"fun123"
}

###
// USERS
GET http://localhost:3000/api/users HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE4YjE5ZWNlN2U3ZTlkZmE3ZTI2MzciLCJuYW1lIjoiTGVvbmFyZG8gU2V2ZXJpbmkiLCJ0eXBlIjowLCJpYXQiOjE2NzkzNDEyNTh9.rEDfphqk_iFexI3DfDIvTMZuamRODMStQnSrBxhaAt8

###
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "user" : "funkey",
    "name": "FunKey Labs",
    "email": "funkeylabs2023@gmail.com",
    "telephone": "123456789",
    "password": "fun123",
    "type": 0,
    "avatar": "this_is_an_avatar"
}

###
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "user" : "leonardo",
    "name": "Leonardo Severini",
    "email": "funkeylabs2023@gmail.com",
    "telephone": "123456789",
    "password": "fun123",
    "type": 0,
    "avatar": "https://res.cloudinary.com/dwp7yvmmw/image/upload/c_thumb,w_200,g_face/v1679339745/avatars/fdktbjbn5zwflbcwbem9.jpg"
}


// CATALOG
###

GET http://localhost:3000/api/catalog HTTP/1.1

###

POST http://localhost:3000/api/catalog HTTP/1.1
content-type: application/json

{
"name": "Fliki",
"link": "fliki.ai",
"short": "Create videos from scripts or blog posts using realistic voices in 2 minutes! Transform blog articles into videos",
"description": "Create videos from scripts or blog posts using realistic voices in 2 minutes! Transform blog articles into videos",
"models": ["Freemium"],
"categories": ["Video Generator"],
"features":  ["feature1", "feature2"],
"haveApi": true,
"images": [""],
"tags": ["video", "freemium"]
}

###

GET http://localhost:3000/api/lists HTTP/1.1

POST http://localhost:3000/api/lists HTTP/1.1
content-type: application/json

{
    "name": "tag3",
    "type": 1
}